[package]
name = "Umriss"
version = "0.1.0"
edition = "2024"

[dependencies]
euclid = "0.22.11"
image = "0.25.5"
itertools = "0.14.0"
num-traits = "0.2.19"
vector2d = "3.1.1"

[dev-dependencies]
test-case = "3.3.1"
