[package]
name = "Umriss"
version = "0.1.0"
edition = "2021"

[dependencies]
euclid = "0.22.11"
image = "0.25.4"
itertools = "0.13.0"
num-traits = "0.2.19"
vector2d = "2.2.0"

[dev-dependencies]
test-case = "3.3.1"
